# Site settings
title: Wes Cook
email: im@wescook.ca
description: Personal webpage
baseurl: ""
url: "https://wescook.ca"

# Build settings
markdown: kramdown
permalink: :categories/:title/
sass:
  style: compressed
plugins:
  - jekyll-redirect-from
